# Generated by Django 3.0.9 on 2020-08-08 00:54

from django.db import migrations
import django_summernote.fields


class Migration(migrations.Migration):

    dependencies = [
        ('learning_logs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='text',
            field=django_summernote.fields.SummernoteTextField(),
        ),
    ]
