# Generated by Django 3.0.9 on 2020-08-04 00:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todolist', '0002_auto_20200803_2014'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todolist',
            name='created',
            field=models.DateField(default='Tue Aug 04 2020 | 0024'),
        ),
        migrations.AlterField(
            model_name='todolist',
            name='due',
            field=models.DateField(default='Tue Aug 04 2020 | 0024'),
        ),
    ]
