# Generated by Django 3.0.9 on 2020-08-04 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todolist', '0003_auto_20200803_2024'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todolist',
            name='created',
            field=models.DateField(default='2020-08-04'),
        ),
        migrations.AlterField(
            model_name='todolist',
            name='due',
            field=models.DateField(default='2020-08-04'),
        ),
    ]
